[build]
  command = "npm run build"
  publish = "dist"

# Ensure SPA routing still serves index.html if needed (not strictly necessary here)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
